development: 
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket: "dcu-fyp"
  region: "eu-west-1"


production:
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket: "dcu-fyp"
  region: "eu-west-1"

